name: Build Example

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      working-directory:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.platform == 'ios' && 'macos-latest' || 'ubuntu-latest' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup Java
        if: ${{ inputs.platform == 'android' }}
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
      - name: Setup Flutter
        uses: ./.github/actions/setup
      - name: Build Android
        if: ${{ inputs.platform == 'android' }}
        working-directory: ${{ inputs.working-directory }}
        run: flutter build apk --debug
      - name: Build iOS
        if: ${{ inputs.platform == 'ios' }}
        working-directory: ${{ inputs.working-directory }}
        run: flutter build ios --debug --no-codesign
