name: Dart CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install essentials from apt
        run: apt-get update --quiet --yes && apt-get install --quiet --yes unzip apt-utils
      - name: Set PATH for pub executables
        run: export PATH="$PATH":"$HOME/.pub-cache/bin"
      - name: Install FVM
        run: fvm install
      - name: Install dependencies
        run: fvm flutter pub get
      - name: Run tests
        run: fvm flutter test
