name: Dart CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install essentials from apt
        run: apt-get update --quiet --yes && apt-get install --quiet --yes unzip apt-utils
      - name: Install FVM
        run: pub global activate fvm 1.3.7
      - name: Install Flutter
        run: fvm install
      - name: Install dependencies
        run: fvm flutter pub get
      - name: Run tests
        run: fvm flutter test
