name: Flutter CI

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Testing
    uses: ./.github/workflows/test.yml

  analyze:
    name: Static Analysis
    uses: ./.github/workflows/analyze.yml

  release:
    needs:
      - test
      - analyze
    name: Release
    uses: ./.github/workflows/release.yml

  publish:
    needs:
      - release
    name: Publish
    uses: ./.github/workflows/publish.yml